export default {
  autofocus: false,
  autoHighlight: false,
  autoSuggest: true,
  disabled: false,
  filterable: true,
  filteredOptions: [],
  item: { id: null, label: null },
  lazyLoading: false,
  limit: null,
  loading: false,
  name: 'selecty',
  noResults: { show: true, label: 'No results found.' },
  onBlur: () => {},
  onChange: () => {},
  onClicked: () => {},
  onFilter: false,
  onFocus: () => {},
  onKeyDown: false,
  onFiltered: () => {},
  onSelected: () => {},
  optLabel: 'label',
  optValue: 'value',
  options: [],
  optionGroups: [],
  placeholder: '',
  required: false,
  sortable: false,
  tabIndex: 1,
  typedValue: '',
  value: '',
  visible: false,
};
